# Cloud Build configuration for Pabbly Mapper
#
# PREREQUISITOS (ejecutar ANTES del deploy):
# 1. Crear secret para API_KEY:
#    gcloud secrets create pabbly-mapper-api-key --replication-policy="automatic"
#    echo -n "tu-api-key-segura" | gcloud secrets versions add pabbly-mapper-api-key --data-file=-
#
# 2. Crear secret para GITHUB_TOKEN:
#    gcloud secrets create pabbly-mapper-github-token --replication-policy="automatic"
#    echo -n "ghp_xxx" | gcloud secrets versions add pabbly-mapper-github-token --data-file=-
#
# 3. Dar permisos al service account de Cloud Run:
#    gcloud secrets add-iam-policy-binding pabbly-mapper-api-key \
#      --member="serviceAccount:PROJECT_NUMBER-compute@developer.gserviceaccount.com" \
#      --role="roles/secretmanager.secretAccessor"
#
#    gcloud secrets add-iam-policy-binding pabbly-mapper-github-token \
#      --member="serviceAccount:PROJECT_NUMBER-compute@developer.gserviceaccount.com" \
#      --role="roles/secretmanager.secretAccessor"
#
# EJECUCION:
#    cd services/pabbly-mapper
#    gcloud builds submit --config cloudbuild.yaml

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pabbly-mapper:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pabbly-mapper:latest'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pabbly-mapper:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pabbly-mapper:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pabbly-mapper'
      - '--image=gcr.io/$PROJECT_ID/pabbly-mapper:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--timeout=60s'
      - '--set-env-vars=GITHUB_OWNER=javiercuervo,GITHUB_REPO=automation-brain,OUTPUT_MODE=repository_dispatch'
      - '--set-secrets=API_KEY=pabbly-mapper-api-key:latest,GITHUB_TOKEN=pabbly-mapper-github-token:latest'

# Opciones de build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

# Imagenes a guardar en Container Registry
images:
  - 'gcr.io/$PROJECT_ID/pabbly-mapper:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pabbly-mapper:latest'

# Timeout del build
timeout: '600s'
